name: iamdog
favicon: null
layout_spectrum: 0.910473
typography_spectrum: 0
title: desigNed OMniscient guArDian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-45802757-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#027e7e'
    - '#6b15ea'
    - '#e7692c'
    - '#98c9cd'
    - '#f2ebff'
  brandStrength: 0.697635
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
