analytics:
  google: UA-45802757-1
color:
  brandColors:
    - '#000000'
    - '#703000'
    - '#A85850'
    - '#F07018'
    - '#F8D868'
  brandStrength: 0.697635
  lightness: 0
  rhythmicContrast: 0
  saturation: 0.5
cta: {}
layout_spectrum: 0.910473
name: iamdog
opengraph: {}
purpose: []
typography_spectrum: 0
