name: iamdog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00492
title: desigNed OMniscient guArDian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-45802757-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191410'
    - '#e1b288'
    - '#94714b'
    - '#a4141a'
    - '#c93d1f'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
